language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

jobs:
  include:
    - stage: with-attributes
      php: 8.0
      before_script:
        - composer require b2pweb/bdf-form-attribute
      script:
        - composer tests

install:
  - travis_retry composer install

script:
  - composer tests
